### ISSUE TITLE
create fails on "Downloading WordPress"

### ISSUE THREAD

**Issue by dhuyvetter** [10up/wp-local-docker-v2#11]
When trying to create a new Docker I keep getting stuck on the "Downloading WordPress" stage. The error thrown seems to be a time-out error.

Is there any way to set the timeout higher or to use a previously downloaded WordPress install?

The error:

> Downloading WordPress
> Error: Failed to get url 'https://api.wordpress.org/core/version-check/1.6/?locale=en_US': cURL error 28: Resolving timed out after 10518 milliseconds.
> (node:12327) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose exec phpfpm su -s /bin/bash www-data -c "wp core download --force"
>     at checkExecSyncError (child_process.js:622:11)
>     at execSync (child_process.js:659:13)
>     at Object.download (/home/dimi/Development/wp-local-docker-v2/src/wordpress.js:9:5)
> (node:12327) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:12327) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by adamsts** [comment]
@dhuyvetter No idea if this applies to your situation but I got this error when using in a virtual machine with a NAT network connection. If I change the connection type to bridged the download is successful and creating the environment can continue.

**Comment by jrtashjian** [comment]
I'm on Ubuntu 19.04 with all dependencies installed and working properly. When running `10updocker create` and selecting to install WordPress I'm also running into this error. Below are installed versions of `docker` and `docker-compose` as well as containers, images, and those running after creating a new environment named `wordpress`. I also included the entire output of the command.

You can see from `docker network ls` that both networks created by 10updocker are in bridge. The top three networks are created by docker and can't be removed.

I'm not sure how to debug further. Hitting that url works on the host machine and I've been able to use wp-cli on the host machine to download and install WordPress locally.

```
$ 10updocker create 
WARNING: No swap limit support
? What is the primary hostname for your site? (Ex: docker.test) wordpress
? Are there additional domains the site should respond to? No
? Do you want to set a proxy for media assets? (i.e. Serving /uploads/ directory assets from a production site) No
? What version of PHP would you like to use? 7.3
? Do you need Elasticsearch No
? Do you want to install WordPress? Yes
? Select a WordPress installation type: Single Site
? Do you want to remove the default content? Yes
? Site Name wordpress
? Admin Username admin
? Admin Password password
? Admin Email admin@example.com
Ensuring global network exists
 - Network exists
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
global_gateway_1 is up-to-date
global_mailcatcher_1 is up-to-date
global_mysql_1 is up-to-date
global_dns_1 is up-to-date
global_phpmyadmin_1 is up-to-date
Waiting for mysql...

Copying required files...
Generating docker-compose.yml file...
done
Generating wp-cli.yml file...
done
Creating database
Locating project files for wordpress
Starting docker containers for wordpress
Creating network "wordpress_default" with the default driver
Creating wordpress_memcached_1 ... done
Creating wordpress_memcacheadmin_1 ... done
Creating wordpress_phpfpm_1        ... done
Creating wordpress_nginx_1         ... done

Downloading WordPress
Error: Failed to get url 'https://api.wordpress.org/core/version-check/1.6/?locale=en_US': cURL error 28: Resolving timed out after 10519 milliseconds.
(node:30718) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose exec phpfpm su -s /bin/bash www-data -c "wp core download --force"
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.download (/home/jrtashjian/.npm-global/lib/node_modules/wp-local-docker/src/wordpress.js:9:5)
(node:30718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
$ 10updocker --version
WP Local Docker
Version 2.5.0
```

```
$ docker --version
Docker version 18.09.7, build 2d0083d
```

```
$ docker-compose --version
docker-compose version 1.21.0, build unknown
```

```
$ docker container ls
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                            NAMES
7ca7cb7cf4e2        nginx:latest              "nginx -g 'daemon of…"   3 minutes ago       Up 3 minutes        80/tcp, 443/tcp                                  wordpress_nginx_1
b52954dedd03        10up/phpfpm:7.3           "/entrypoint.sh php-…"   3 minutes ago       Up 3 minutes        9000/tcp                                         wordpress_phpfpm_1
18f49fcd8bc3        hitwe/phpmemcachedadmin   "docker-php-entrypoi…"   3 minutes ago       Up 3 minutes        80/tcp                                           wordpress_memcacheadmin_1
7ac3887d6d35        memcached:latest          "docker-entrypoint.s…"   3 minutes ago       Up 3 minutes        11211/tcp                                        wordpress_memcached_1
2943c4fd1f4e        phpmyadmin/phpmyadmin     "/docker-entrypoint.…"   8 minutes ago       Up 8 minutes        0.0.0.0:8092->80/tcp                             global_phpmyadmin_1
95687ef25663        andyshinn/dnsmasq         "dnsmasq -k -A /test…"   8 minutes ago       Up 8 minutes        53/tcp, 53/udp                                   global_dns_1
95204c07f6fc        schickling/mailcatcher    "mailcatcher --no-qu…"   8 minutes ago       Up 8 minutes        0.0.0.0:1025->1025/tcp, 0.0.0.0:1080->1080/tcp   global_mailcatcher_1
73b9f6b26e31        10up/nginx-proxy          "/app/docker-entrypo…"   8 minutes ago       Up 8 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp         global_gateway_1
b4f7bad45f6f        mysql:5                   "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        0.0.0.0:3306->3306/tcp, 33060/tcp                global_mysql_1
```

```
$ docker image ls
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
nginx                     latest              f68d6e55e065        3 days ago          109MB
10up/nginx-proxy          latest              bb5f26d726cb        9 days ago          148MB
memcached                 latest              de8ed9aa9b7e        3 weeks ago         67.5MB
mysql                     5                   a1aa4f76fab9        3 weeks ago         373MB
hitwe/phpmemcachedadmin   latest              86ac958ece51        3 weeks ago         423MB
phpmyadmin/phpmyadmin     latest              626319eaebed        3 weeks ago         421MB
10up/phpfpm               7.3                 52cf4d8ea488        5 months ago        688MB
hello-world               latest              fce289e99eb9        6 months ago        1.84kB
schickling/mailcatcher    latest              a92223e5253a        12 months ago       86.4MB
andyshinn/dnsmasq         latest              831c17422076        15 months ago       4.88MB
```

```
$ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                            NAMES
7ca7cb7cf4e2        nginx:latest              "nginx -g 'daemon of…"   8 minutes ago       Up 8 minutes        80/tcp, 443/tcp                                  wordpress_nginx_1
b52954dedd03        10up/phpfpm:7.3           "/entrypoint.sh php-…"   8 minutes ago       Up 8 minutes        9000/tcp                                         wordpress_phpfpm_1
18f49fcd8bc3        hitwe/phpmemcachedadmin   "docker-php-entrypoi…"   8 minutes ago       Up 8 minutes        80/tcp                                           wordpress_memcacheadmin_1
7ac3887d6d35        memcached:latest          "docker-entrypoint.s…"   8 minutes ago       Up 8 minutes        11211/tcp                                        wordpress_memcached_1
2943c4fd1f4e        phpmyadmin/phpmyadmin     "/docker-entrypoint.…"   12 minutes ago      Up 12 minutes       0.0.0.0:8092->80/tcp                             global_phpmyadmin_1
95687ef25663        andyshinn/dnsmasq         "dnsmasq -k -A /test…"   13 minutes ago      Up 12 minutes       53/tcp, 53/udp                                   global_dns_1
95204c07f6fc        schickling/mailcatcher    "mailcatcher --no-qu…"   13 minutes ago      Up 12 minutes       0.0.0.0:1025->1025/tcp, 0.0.0.0:1080->1080/tcp   global_mailcatcher_1
73b9f6b26e31        10up/nginx-proxy          "/app/docker-entrypo…"   13 minutes ago      Up 12 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp         global_gateway_1
b4f7bad45f6f        mysql:5                   "docker-entrypoint.s…"   13 minutes ago      Up 12 minutes       0.0.0.0:3306->3306/tcp, 33060/tcp                global_mysql_1
```

```
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
40c3f31df545        bridge              bridge              local
ea8f190ae698        host                host                local
6aced6f5e51c        none                null                local
3d0dc68e6dd0        wordpress_default   bridge              local
6cb5c73e6f6d        wplocaldocker       bridge              local
```

**Comment by jrtashjian** [comment]
I've also attempted to create an environment with the "Core Development Version" option which fails on cloning the git repository.

```
10updocker create          
WARNING: No swap limit support
? What is the primary hostname for your site? (Ex: docker.test) wordpress-dev
? Are there additional domains the site should respond to? No
? Do you want to set a proxy for media assets? (i.e. Serving /uploads/ directory assets from a production site) No
? What version of PHP would you like to use? 7.3
? Do you need Elasticsearch No
? Do you want to install WordPress? Yes
? Select a WordPress installation type: Core Development Version
? Do you want to remove the default content? Yes
? Site Name wordpress-dev
? Admin Username admin
? Admin Password password
? Admin Email admin@example.com
Ensuring global network exists
 - Network exists
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
global_mysql_1 is up-to-date
global_gateway_1 is up-to-date
global_mailcatcher_1 is up-to-date
global_dns_1 is up-to-date
global_phpmyadmin_1 is up-to-date
Waiting for mysql...

Copying required files...
Generating docker-compose.yml file...
done
Generating wp-cli.yml file...
done
Creating database
Locating project files for wordpress-dev
Starting docker containers for wordpress-dev
Creating network "wordpress-dev_default" with the default driver
Creating wordpress-dev_memcached_1 ... done
Creating wordpress-dev_memcacheadmin_1 ... done
Creating wordpress-dev_phpfpm_1        ... done
Creating wordpress-dev_nginx_1         ... done

Downloading WordPress Develop
Cloning into '.'...
fatal: Unable to look up develop.git.wordpress.org (port 9418) (Temporary failure in name resolution)
(node:1630) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose exec phpfpm su -s /bin/bash www-data -c "git clone git://develop.git.wordpress.org/ ."
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:653:13)
    at Object.downloadDevelop (/home/jrtashjian/.npm-global/lib/node_modules/wp-local-docker/src/wordpress.js:16:5)
(node:1630) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1630) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ARAGATO** [comment]
Same issue here, were you able to resolve it?

**Comment by cinghaman** [comment]
The same issue, everything is on the latest version, anyone found a solution I can't run/install WP setup my projects

docker-compose --version
docker-compose version 1.25.5, build 8a1c60f6

10updocker --version
WP Local Docker
Version 2.7.0

docker --version
Docker version 19.03.8, build afacb8b

**Comment by esa1975** [comment]
@cinghaman is this on your local machine or in a VM? My issue was running it in a VM. I've never run it locally. If you are having an issue with local install maybe try KVM or something to see if you can isolate the problem. Also, I've found the performance in a VM perfectly adequate with the added bonuses of being self-contained and portable. The only downside is needing to manage your hosts file manually vs. having WPLD do it for you. Really not a big deal though.

**Comment by varvino** [comment]
I'm running a Virtualbox with Xubuntu 20.0.4 LTS. Network mode is set to Bridged. I still am unable to download WordPress, which is weird. I was running Xubuntu 18.x.x LTS and 10updocker worked on that.

`docker -v
Docker version 19.03.12, build 48a66213fe
`

`docker-compose -v
docker-compose version 1.26.1, build f216ddbf
`

`10updocker -v
WP Local Docker
Version 2.7.0
`
