### ISSUE TITLE
Error on create - Failed to cURL Wordpress API - cURL Error 28

### ISSUE THREAD

**Issue by ARAGATO** [10up/wp-local-docker-v2#115]
**Describe the bug**
Fresh install of 10updocker. Just did a 10updocker create and everything work well up tot the Download Wordpress step.

```
? What is the primary hostname for your site? (Ex: docker.test) acms.test
? Are there additional domains the site should respond to? No
? Do you want to enable HTTPS? No
? Do you want to set a proxy for media assets? (i.e. Serving /uploads/ directory assets from a production
 site) No
? What version of PHP would you like to use? 7.3
? Do you need Elasticsearch No
? Do you want to install WordPress? Yes
? Select a WordPress installation type: Single Site
? Do you want to remove the default content? Yes
? Site Name acms.test
? Admin Username admin
? Admin Password password
? Admin Email admin@acms.test
Ensuring global network exists
 - Network exists
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
global_dns_1 is up-to-date
global_mailcatcher_1 is up-to-date
global_gateway_1 is up-to-date
global_mysql_1 is up-to-date
global_phpmyadmin_1 is up-to-date
Waiting for mysql...

Copying required files...
Generating docker-compose.yml file...
done
Generating wp-cli.yml file...
done
Creating database
Locating project files for acms-test
Starting docker containers for acms-test
Creating network "acms-test_default" with the default driver
Creating acms-test_memcached_1 ... done
Creating acms-test_phpfpm_1    ... done
Creating acms-test_nginx_1     ... done

Downloading WordPress
Error: Failed to get url 'https://api.wordpress.org/core/version-check/1.7/?locale=en_US': cURL error 28: Resolving timed out after 10000 milliseconds.
(node:85716) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose exec phpfpm wp core download --force
    at checkExecSyncError (child_process.js:611:11)
    at execSync (child_process.js:647:15)
    at Object.download (/usr/lib/node_modules/wp-local-docker/src/wordpress.js:9:5)
    at async createEnv (/usr/lib/node_modules/wp-local-docker/src/create.js:417:13)
    at async Object.command (/usr/lib/node_modules/wp-local-docker/src/create.js:471:13)
    at async init (/usr/lib/node_modules/wp-local-docker/index.js:67:13)
(node:85716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:85716) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to Reproduce**
1. 10updocker create

**Expected behavior**
Installation succeeds

**Environment information**
 - Device: Thinkpad X1 Carbon
 - OS: Manjaro Linux 20.0
- NPM: 6.14.4
- Node: 13.13.0

**Comment by ARAGATO** [comment]
So, after hours of research was able to pin point the issue.
It s the Google Nameservers.

I had them setup on my router as the default nameservers 8.8.8.8 and 8.8.4.4 respectively.
After changing those the issue resolved.
