### ISSUE TITLE
phpfpm container creation fails (mkdir file exists)

### ISSUE THREAD

**Issue by Viper007Bond** [10up/wp-local-docker-v2#15]
While running `10docker create` on Windows for the very first time:

```
Creating syntaxhighlighter-localhost_phpfpm_1        ... error

ERROR: for syntaxhighlighter-localhost_phpfpm_1  Cannot start service phpfpm: error while creating mount source path '/host_mnt/c/work/wpdev/wp-local-docker-sites/syntaxhighlighter-localhost/config/php-fpm/wp-cli.local.yml': mkdir /host_mnt/c: file exists

ERROR: for phpfpm  Cannot start service phpfpm: error while creating mount source path '/host_mnt/c/work/wpdev/wp-local-docker-sites/syntaxhighlighter-localhost/config/php-fpm/wp-cli.local.yml': mkdir /host_mnt/c: file exists
ERROR: Encountered errors while bringing up the project.

Downloading WordPress
ERROR: No container found for phpfpm_1
(node:19240) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose exec phpfpm su -s /bin/bash www-data -c "wp core download --force"
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at Object.download (C:\Users\viper\AppData\Roaming\nvm\v8.15.0\node_modules\wp-local-docker\src\wordpress.js:9:5)
    at <anonymous>
(node:19240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

`/config/php-fpm/wp-cli.local.yml` does indeed already exist.

**Comment by Viper007Bond** [comment]
I deleted and started over and it worked the second time around. 🤷‍♂️
