### ISSUE TITLE
Error on create

### ISSUE THREAD

**Issue by cgsmith** [10up/wp-local-docker-v2#170]
I am running into this issue...

```
Starting global_gateway_1 ... error

ERROR: for global_gateway_1  Cannot start service gateway: driver failed programming external connectivity on endpoint global_gateway_1 (e84ed7237f070162578dd1688503574e8d39714f836d7d99befa13a2378c6b1f): Error starting userland proxy: listen tcp4 127.0.0.1:80: bind: address already in use

ERROR: for gateway  Cannot start service gateway: driver failed programming external connectivity on endpoint global_gateway_1 (e84ed7237f070162578dd1688503574e8d39714f836d7d99befa13a2378c6b1f): Error starting userland proxy: listen tcp4 127.0.0.1:80: bind: address already in use
ERROR: Encountered errors while bringing up the project.
(node:63684) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose up -d
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at startGateway (/home/chris/.npm-global/lib/node_modules/wp-local-docker/src/gateway.js:90:9)
    at Object.startGlobal (/home/chris/.npm-global/lib/node_modules/wp-local-docker/src/gateway.js:119:11)
    at async createEnv (/home/chris/.npm-global/lib/node_modules/wp-local-docker/src/create.js:235:5)
    at async Object.command (/home/chris/.npm-global/lib/node_modules/wp-local-docker/src/create.js:471:13)
    at async init (/home/chris/.npm-global/lib/node_modules/wp-local-docker/index.js:67:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:63684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:63684) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by McCallumDillon** [comment]
@cgsmith are you OSX and did you recently upgrade to Big Sur? I had this same issue after upgrade to BigSur. The issue was docker couldn't/wouldn't even start thus no 10updocker commands are going to fire. Completely uninstalling docker and reinstalling– then reinstalling 10updocker-v2 seemed to do the trick and resolve the problem for me.

**Comment by tylercherpak** [comment]
Hey @cgsmith 

Are you still having this issue? Please check the [troubleshooting section](https://github.com/10up/wp-local-docker-v2/#i-am-having-issues-with-wp-local-docker-what-are-the-best-troubleshooting-techniques) if so. If that still doesn't resolve this for you, feel free to comment on this and I can reopen the issue. Thanks!

**Comment by cgsmith** [comment]
I moved to vvv
