### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by davingreen** [10up/wp-local-docker-v2#225]
**Describe the bug**
Verified that docker, docker-compose, and node 16 is installed.

On install as a local or global package, I get errors:

**Steps to Reproduce**
Attempt to install on linux (tried Ubuntu and Amazon Linux)
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /home/ec2-user/node_modules/nodegit
npm ERR! command failed
npm ERR! command sh -c node lifecycleScripts/preinstall && node lifecycleScripts/install
npm ERR! [nodegit] Running pre-install script
npm ERR! [nodegit] Running install script
npm ERR! Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ec2-user/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/ec2-user/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp
npm ERR! info it worked if it ends with ok
npm ERR! node-pre-gyp info
npm ERR! using node-pre-gyp@0.13.0
npm ERR! node-pre-gyp info using node@16.6.0 | linux | x64     
npm ERR! node-pre-gyp
npm ERR!
npm ERR! WARN
npm ERR!
npm ERR! Using request for node-pre-gyp https download
npm ERR!
npm ERR! node-pre-gyp
npm ERR! info check checked for "/home/ec2-user/node_modules/nodegit/build/Release/nodegit.node" (not found)
npm ERR! node-pre-gyp
npm ERR! http GET https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp
npm ERR! http 404 https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp
npm ERR! WARN Tried to download(404): https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not found for nodegit@0.27.0 and node@16.6.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp http 404 status code downloading tarball 
https://axonodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.27.0-node-v93-linux-x64.tar.gz
npm ERR! gyp
npm ERR! info
npm ERR! it worked if it ends with ok
npm ERR! gyp
npm ERR! info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.0 | linux | x64
npm ERR! gyp
npm ERR! info ok
npm ERR! gyp
npm ERR! info
npm ERR! it worked if it ends with ok
npm ERR! gyp info
npm ERR! using node-gyp@7.1.2
npm ERR! gyp
npm ERR! info using node@16.6.0 | linux | x64
npm ERR! gyp
npm ERR! info find Python using Python version 3.7.10 found at 
"/usr/bin/python3"
npm ERR! gyp
npm ERR! http GET https://nodejs.org/download/release/v16.6.0/node-v16.6.0-headers.tar.gz
npm ERR! gyp
npm ERR! http 200 https://nodejs.org/download/release/v16.6.0/node-v16.6.0-headers.tar.gz
npm ERR! gyp
npm ERR! http GET https://nodejs.org/download/release/v16.6.0/SHASUMS256.txt
npm ERR! gyp
npm ERR! http 200 https://nodejs.org/download/release/v16.6.0/SHASUMS256.txt
npm ERR! (node:8942) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the 
warning was created)
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn
npm ERR! /usr/bin/python3
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! [
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! 'binding.gyp',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! '-f',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! 'make',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! '-I',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! '/home/ec2-user/node_modules/nodegit/build/config.gypi',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! '-I',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! '-I',
npm ERR! gyp
npm ERR!
npm ERR! info
npm ERR!
npm ERR! spawn args
npm ERR! '/home/ec2-user/.cache/node-gyp/16.6.0/include/node/common.gypi',
npm ERR! gyp
npm ERR! info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/ec2-user/.cache/node-gyp/16.6.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/ec2-user/.cache/node-gyp/16.6.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ec2-user/node_modules/nodegit',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: krb5-config: command not found
npm ERR! gyp: Call to 'krb5-config gssapi --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp
npm ERR! ERR! configure error
npm ERR! gyp ERR!
npm ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR!
npm ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp
npm ERR! ERR! System Linux 4.14.238-182.422.amzn2.x86_64       
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/ec2-user/node_modules/nodegit/build/Release/nodegit.node" "--module_name=nodegit" "--module_path=/home/ec2-user/node_modules/nodegit/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /home/ec2-user/node_modules/nodegit      
npm ERR! gyp ERR!
npm ERR! node -v v16.6.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp
npm ERR! ERR! not ok
npm ERR! node-pre-gyp
npm ERR! ERR! build error
npm ERR! node-pre-gyp
npm ERR! ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ec2-user/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/home/ec2-user/node_modules/nodegit/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ec2-user/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp
npm ERR! ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR!
npm ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp
npm ERR! ERR! System Linux 4.14.238-182.422.amzn2.x86_64       
npm ERR! node-pre-gyp ERR!
npm ERR! command "/usr/bin/node" "/home/ec2-user/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd
npm ERR! /home/ec2-user/node_modules/nodegit
npm ERR! node-pre-gyp ERR! node -v v16.6.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.13.0
npm ERR! node-pre-gyp ERR!
npm ERR! not ok
npm ERR! [nodegit] ERROR - Could not finish install
npm ERR! [nodegit] ERROR - finished with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2021-08-01T20_58_55_098Z-debug.log
```

**Environment information**
 - OS: Linux

**Additional context**
If it's something unrelated to this package, can you please point me in the right direction?

**Comment by tylercherpak** [comment]
This should be resolved in the latest version. Let me know if anyone is still experiencing issues! 😄
