### ISSUE TITLE
Error installing on Windows 10

### ISSUE THREAD

**Issue by robisonweb** [10up/wp-local-docker-v2#230]
I'm having trouble installing **wp-local-docker-v2** on Windows 10 VS Code, Node.js 14.17.5, docker-compose 1.29.2.

I tried to install only NVM from https://github.com/nvm-sh/nvm  but I was unsuccessful.

I got the zip on https://github.com/10up/wp-local-docker-v2 

Run command install: **$ npm install -g wp-local-docker** but it generated an error.

Error message:
```
robis@Robison-I3 MINGW64 /d/Projetos/www/_wp_local_docker
$ npm install -g wp-local-docker
npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped 
node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use 
Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
C:\Users\robis\AppData\Roaming\npm\10updocker -> C:\Users\robis\AppData\Roaming\npm\node_modules\wp-local-docker\index.js
C:\Users\robis\AppData\Roaming\npm\10updocker-hosts -> C:\Users\robis\AppData\Roaming\npm\node_modules\wp-local-docker\hosts.js

> mkcert-prebuilt@1.0.0 install C:\Users\robis\AppData\Roaming\npm\node_modules\wp-local-docker\node_modules\mkcert-prebuilt
> node install.js


> nodegit@0.27.0 install C:\Users\robis\AppData\Roaming\npm\node_modules\wp-local-docker\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
WARN Using request for node-pre-gyp https download
[nodegit] Success: "C:\Users\robis\AppData\Roaming\npm\node_modules\wp-local-docker\node_modules\nodegit\build\Release\nodegit.node" is installed via remote
[nodegit] Completed installation successfully.

> nodegit@0.27.0 postinstall C:\Users\robis\AppData\Roaming\npm\node_modules\wp-local-docker\node_modules\nodegit
> node lifecycleScripts/postinstall


> wp-local-docker@2.8.1 postinstall C:\Users\robis\AppData\Roaming\npm\node_modules\wp-local-docker
> npm run 10updocker postinstall --silent

'.' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-local-docker@2.8.1 postinstall: `npm run 10updocker postinstall --silent`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wp-local-docker@2.8.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\robis\AppData\Roaming\npm-cache\_logs\2021-08-12T00_48_05_632Z-debug.log 
```
Link to file ...632Z-debug.log

[2021-08-12T00_48_05_632Z-debug.log](https://github.com/robisonweb/public/blob/master/2021-08-12T00_48_05_632Z-debug.log)

Could someone help me?

**Comment by robisonweb** [comment]
I run a docker-composer up on global folder, but on the Docker-Composer-Desktop screen, Global: Globaldns_1 and Global_gateway_1 weren't running, I clicked to run

**$ 10updocker --version** // After this command in bash, it showed this error:

```
robis@Robison-I3 MINGW64 /d/Projetos/www/_wp_local_docker/global
$ 10updocker --version
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\robis\AppData\Roaming\npm\node_modules\wp-local-docker\index.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```
When I try to install using: **$ npm install -g wp-local-docker**

The node folder `...\npm\node_modules\wp-local-docker\` is created, but when generating an error it is deleted.

**Comment by adrian-ortega** [comment]
I have this exact same problem as @robisonweb 

```
$ 10updocker
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'C:\Users\Adrian Ortega\AppData\Roaming\npm\node_modules\wp-local-docker\index.js'
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:745:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}
```

**Comment by tylercherpak** [comment]
Hey all 👋 

I have removed the `nodegit` dependency on the latest rc release which I think was related to this issue.

You can test this version before it is released by using the next tag.

`npm i -g wp-local-docker@next` to install the rc version and test it.

Let me know if y'all have any questions! 😄
