### ISSUE TITLE
CPU error from CMAKE installing @next on M1 Mac

### ISSUE THREAD

**Issue by pablojmarti** [10up/wp-local-docker-v2#252]
**Describe the bug**
When installing `@next` I get a CMAKE error. Ive installed `cmake` and `nss` via brew. 
```
[ 11%] Building C object CMakeFiles/utils.dir/src/filesystem.c.o
[ 22%] Building C object CMakeFiles/utils.dir/src/stack_line_reader.c.o
[ 33%] Building C object CMakeFiles/utils.dir/src/string_view.c.o
[ 33%] Built target utils
[ 44%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/hwcaps.c.o
[ 55%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/unix_features_aggregator.c.o
[ 55%] Built target unix_based_hardware_detection
[ 66%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_arm.c.o
In file included from /Users/pablo/.nvm/versions/node/v14.17.0/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/src/cpuinfo_arm.c:15:
/Users/pablo/.nvm/versions/node/v14.17.0/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/include/cpuinfo_arm.h:118:2: error: "Including cpuinfo_arm.h from a non-arm target."
#error "Including cpuinfo_arm.h from a non-arm target."
 ^
1 error generated.
make[3]: *** [CMakeFiles/cpu_features.dir/src/cpuinfo_arm.c.o] Error 1
make[2]: *** [CMakeFiles/cpu_features.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [/Users/pablo/.nvm/versions/node/v14.17.0/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/build/libcpu_features.a] Error 2
```
**Steps to Reproduce**
1. Use M1 Mac
2. install @next via `npm i -g wp-local-docker@next`

**Environment information**
 - Device: MacBook Pro 13-inch, M1, 2020 
 - OS: macOS 11.6
 - Docker Desktop version: 4.1.1
- Node: 14.17.0

**Comment by tylercherpak** [comment]
hey @pablojmarti 

Can you run `10updocker configure` and rebuild the default config and see if that resolves the issue for you?

I haven't been able to reproduce this.

Thanks!

**Comment by tylercherpak** [comment]
I'm closing this issue but feel free to reopen this if you are still experiencing this issue. Thanks!

**Comment by s3rgiosan** [comment]
@tylercherpak I continue to get the same errors with the latest version

```
░▒▓ ~/Projects  npm i -g wp-local-docker@next  
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/Users/USER/.nvm/versions/node/v14.18.1/bin/10updocker-hosts -> /Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/hosts.js
/Users/USER/.nvm/versions/node/v14.18.1/bin/10updocker -> /Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/index.js

> cpu-features@0.0.2 install /Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/node_modules/cpu-features
> node-gyp rebuild

  ACTION Configuring dependencies /Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/build/Makefile
-- The C compiler identification is AppleClang 13.0.0.13000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for getauxval
-- Looking for getauxval - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/build
  TOUCH Release/obj.target/config_deps.stamp
  ACTION Building dependencies /Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/build/libcpu_features.a
[ 11%] Building C object CMakeFiles/utils.dir/src/filesystem.c.o
[ 22%] Building C object CMakeFiles/utils.dir/src/stack_line_reader.c.o
[ 33%] Building C object CMakeFiles/utils.dir/src/string_view.c.o
[ 33%] Built target utils
[ 44%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/hwcaps.c.o
[ 55%] Building C object CMakeFiles/unix_based_hardware_detection.dir/src/unix_features_aggregator.c.o
[ 55%] Built target unix_based_hardware_detection
[ 66%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_arm.c.o
In file included from /Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/src/cpuinfo_arm.c:15:
/Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/include/cpuinfo_arm.h:118:2: error: "Including cpuinfo_arm.h from a non-arm target."
#error "Including cpuinfo_arm.h from a non-arm target."
 ^
1 error generated.
make[3]: *** [CMakeFiles/cpu_features.dir/src/cpuinfo_arm.c.o] Error 1
make[2]: *** [CMakeFiles/cpu_features.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [/Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/node_modules/cpu-features/deps/cpu_features/build/libcpu_features.a] Error 2
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/USER/.nvm/versions/node/v14.18.1/bin/node" "/Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/USER/.nvm/versions/node/v14.18.1/lib/node_modules/wp-local-docker/node_modules/cpu-features
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```

**Comment by tylercherpak** [comment]
Hey @s3rgiosan do you have nss installed (`brew install nss`)?

@pablojmarti  was there anything else you needed to do to resolve this for yourself?
