### ISSUE TITLE
Receiving errors when trying to install wp-local-docker

### ISSUE THREAD

**Issue by joecue** [10up/wp-local-docker-v2#285]
**Describe the bug**
I have a brand new Windows 10 install.  I've installed Docker Desktop and have WSL 2 enabled in Docker.  I installed all prerequisites and even installed NVM to drop my NPM level from 16.14.0 to 12.22.10  I originally had 16 installed from an attempt to run VVV again, but I couldn't get that to work so then I went to Docker and 10up to try this for local development.  When I run "npm install -g wp-local-docker" I get the following error.

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! code EEXIST
npm ERR! path C:\Users\jquerin\.nvm\versions\node\v12.22.10\bin\node_modules\wp-local-docker\index.js
npm ERR! dest C:\Users\jquerin\.nvm\versions\node\v12.22.10\bin\10updocker
npm ERR! EEXIST: file already exists, cmd shim 'C:\Users\jquerin\.nvm\versions\node\v12.22.10\bin\node_modules\wp-local-docker\index.js' -> 'C:\Users\jquerin\.nvm\versions\node\v12.22.10\bin\10updocker'
npm ERR! File exists: C:\Users\jquerin\.nvm\versions\node\v12.22.10\bin\10updocker
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jquerin\AppData\Roaming\npm-cache\_logs\2022-02-10T22_16_49_805Z-debug.log

**Steps to Reproduce**
1.) npm install -g wp-local-docker

**Expected behavior**
Containers to be created.

**Environment information**
 - Device: Dell Optiplex
 - OS: Windows 10 20H2
 - Docker Desktop version: 4.4.4 (73704)
 - Browser and version: Chrome 98.0.4758.82, FireFox 97.0
 - WordPress version: N/A (not instlalled yet)

**Comment by joecue** [comment]
Log file mentioned at the end of the bash terminal output.

[2022-02-10T22_16_49_805Z-debug.log](https://github.com/10up/wp-local-docker-v2/files/8049482/2022-02-10T22_16_49_805Z-debug.log)

**Comment by tylercherpak** [comment]
Hey @joecue 

is this only happening on node v12?

Can you see if you can reproduce on node 14 or 16?

Thanks!

**Comment by joecue** [comment]
I just tried with 14 and got something similar but more verbose.

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\10updocker -> C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\index.js
C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\10updocker-hosts -> C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\hosts.js

> cpu-features@0.0.2 install C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\node_modules\cpu-features
> node-gyp rebuild


C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\node_modules\cpu-features>if not defined npm_config_node_gyp (node "C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\jquerin\\.nvm\\versions\\node\\v14.19.0\\bin\\node.exe" "C:\\Users\\jquerin\\.nvm\\versions\\node\\v14.19.0\\bin\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\node_modules\cpu-features
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> ssh2@1.6.0 install C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\node_modules\ssh2
> node install.js


C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\node_modules\ssh2\lib\protocol\crypto>if not defined npm_config_node_gyp (node "C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" --target=v14.19.0 rebuild )  else (node "C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" --target=v14.19.0 rebuild )
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:390:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:402:5)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Users\\jquerin\\.nvm\\versions\\node\\v14.19.0\\bin\\node.exe" "C:\\Users\\jquerin\\.nvm\\versions\\node\\v14.19.0\\bin\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "--target=v14.19.0" "rebuild"
gyp ERR! cwd C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\node_modules\ssh2\lib\protocol\crypto
gyp ERR! node -v v14.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Failed to build optional crypto binding

> mkcert-prebuilt@1.0.0 install C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker\node_modules\mkcert-prebuilt
> node install.js


> wp-local-docker@3.0.2 postinstall C:\Users\jquerin\.nvm\versions\node\v14.19.0\bin\node_modules\wp-local-docker
> npm run 10updocker postinstall --silent

'.' is not recognized as an internal or external command,
operable program or batch file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.2 (node_modules\wp-local-docker\node_modules\cpu-features):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: cpu-features@0.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wp-local-docker@3.0.2 postinstall: `npm run 10updocker postinstall --silent`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wp-local-docker@3.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jquerin\AppData\Roaming\npm-cache\_logs\2022-02-11T14_56_39_365Z-debug.log


[2022-02-11T14_56_39_365Z-debug.log](https://github.com/10up/wp-local-docker-v2/files/8049515/2022-02-11T14_56_39_365Z-debug.log)

Looks like I may need to install Python?

**Comment by joecue** [comment]
Just tried with 16 and got something very similar to 12, which is what I first got when I tried and then noticed a note in the ReadMe about using nvm and downgrading to 12.

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice
npm notice New minor version of npm available! 8.3.1 -> 8.5.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.0>
npm notice Run `npm install -g npm@8.5.0` to update!
npm notice
npm ERR! code 1
npm ERR! path C:\Users\jquerin\.nvm\versions\node\v16.14.0\bin\node_modules\wp-local-docker
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run 10updocker postinstall --silent
npm ERR! '.' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jquerin\AppData\Local\npm-cache\_logs\2022-02-11T14_58_52_166Z-debug-0.log

The referenced log file doesn't exist.

**Comment by joecue** [comment]
@tylercherpak I'm not familiar with that.  This is my first time using Docker, since prior I was on Windows 7 and couldn't run it.  I have the checkbox in Docker Desktop checked to enable WSL2 but I'm not sure how to run it inside?

**Comment by joecue** [comment]
@tylercherpak, so I think I found how to install a linux distro, currently installing Ubuntu 20.04 (it's what I run in AWS) once I have that installed, I'll try and run the install there, but I may some more digging to do find out how.

**Comment by tylercherpak** [comment]
Hey @joecue

So you should be able to just run Docker for Desktop directly on windows (with that wsl2 checkbox).

Then instead of the ubuntu terminal window run node and the wp-local-docker install set up.

**Comment by AleMunin** [comment]
Having a similar problem on the linux side.

I'm using Zorin 15 (based on Ubuntu 18.04 iirc)



` npm install -g wp-local-docker
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 218 packages, and audited 219 packages in 19s

29 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
`

I feel it is worth mentioning it is my first time using Docker and Node, so I figured it was just me doing something silly until I saw this thread.

**Comment by vyawahak** [comment]
@tylercherpak Hi, I am working with @TylerB24890 from Blackstone's team. Basically, even I am facing this . is not recognized as command error on my machine to install. Could you please help me to resolve this issue? 

Here is the error I am getting:

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path C:\Users\vyawahak\AppData\Roaming\npm\node_modules\wp-local-docker
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run 10updocker postinstall --silent
npm ERR! '.' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vyawahak\AppData\Local\npm-cache\_logs\2022-02-25T07_05_01_971Z-debug-0.log
```
Also, I am attaching the debug-log specified above.
[2022-02-25T07_05_01_971Z-debug-0.log](https://github.com/10up/wp-local-docker-v2/files/8139196/2022-02-25T07_05_01_971Z-debug-0.log)

Please let me know if you could help me resolving this issue as soon as possible.

**Comment by tylercherpak** [comment]
Hi all,

I want to confirm we are running these npm commands from inside the wsl2 linux terminal.

wp-local-docker only works when run through a linux install such as ubuntu. If you need help setting up wsl 2 linux shell you can look at [this guide](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview).

Let me know if you have questions.

**Comment by vyawahak** [comment]
Hi @tylercherpak,

Thank you for your response on this. On the WSL I am getting another issue as mentioned below:

```
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to versi
[2022-02-28T16_09_10_864Z-debug-0.log](https://github.com/10up/wp-local-docker-v2/files/8155202/2022-02-28T16_09_10_864Z-debug-0.log)
on 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice
npm notice New minor version of npm available! 8.3.1 -> 8.5.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.2
npm notice Run npm install -g npm@8.5.2 to update!
npm notice
npm ERR! code 1
npm ERR! path /home/vyawahak/.asdf/installs/nodejs/17.4.0/.npm/lib/node_modules/wp-local-docker/node_modules/mkcert-prebuilt
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Error: unable to get local issuer certificate
npm ERR!     at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
npm ERR!     at TLSSocket.emit (node:events:520:28)
npm ERR!     at TLSSocket._finishInit (node:_tls_wrap:944:8)
npm ERR!     at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vyawahak/.npm/_logs/2022-02-28T16_09_10_864Z-debug-0.log
```

Also, I attached the log for your reference. 

Could you please help me on this?

**Comment by tylercherpak** [comment]
`npm ERR! Error: unable to get local issuer certificate` This appears to be an issue with generating the certifcates.

Does `mkcert` work properly on your machine? Separately from wp-local-docker? This is what wpld uses under the hood. You need to be able to generate self signed certs locally for wpld to work properly.

**Comment by vyawahak** [comment]
Hi @tylercherpak ,

I did have a discussion with our ops team. They told me that we are using zScaler certificates and that's why it might be blocking mkcert to create certificates. Could you please help to with making it compatible with zScaler certificates? 

Looking forward to hearing from you!

**Comment by tylercherpak** [comment]
Hey @vyawahak 

zScaler certificates would be out side the scope of this open source project. With your use case and environmental restrictions, you may be better served to create a custom docker compose file that specifically works with your requirements. 

Let me know if you have any questions!
