### ISSUE TITLE
MySQL fails to login

### ISSUE THREAD

**Issue by selfagency** [10up/wp-local-docker-v2#43]
```
Ensuring global network exists
 - Creating network
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
Creating volume "global_mysqlData" with default driver
Pulling dns (andyshinn/dnsmasq:)...
latest: Pulling from andyshinn/dnsmasq
1eae7a7426b0: Pull complete
4e20cc818d2e: Pull complete
Pulling gateway (10up/nginx-proxy:)...
latest: Pulling from 10up/nginx-proxy
a5a6f2f73cd8: Pull complete
2343eb083a4e: Pull complete
251439d5b33c: Pull complete
0150289a3195: Pull complete
196dcbce1a9b: Pull complete
8826dc3389ea: Pull complete
c7a4bc596c6f: Pull complete
8000a1ad9fc5: Pull complete
3bea426c29a7: Pull complete
8378fe8463bb: Pull complete
2b9069032ffe: Pull complete
7d5208048df2: Pull complete
448d61fe20c7: Pull complete
Pulling mysql (mysql:5)...
5: Pulling from library/mysql
743f2d6c1f65: Pull complete
3f0c413ee255: Pull complete
aef1ef8f1aac: Pull complete
f9ee573e34cb: Pull complete
3f237e01f153: Pull complete
f9da32e8682a: Pull complete
4b8da52fb357: Pull complete
6f38e9cfd49b: Pull complete
9f4834b3f44f: Pull complete
af631d92fdba: Pull complete
0e771ddab25c: Pull complete
Pulling mailcatcher (schickling/mailcatcher:)...
latest: Pulling from schickling/mailcatcher
605ce1bd3f31: Pull complete
0a2affcb9058: Pull complete
075a89310b88: Pull complete
2f13f0ce4036: Pull complete
f54de890ef53: Pull complete
Pulling phpmyadmin (phpmyadmin/phpmyadmin:)...
latest: Pulling from phpmyadmin/phpmyadmin
743f2d6c1f65: Already exists
6307e89982cc: Pull complete
807218e72ce2: Pull complete
5108df1d03f8: Pull complete
901e0b6a7fe5: Pull complete
5ffe11e7ab2c: Pull complete
da5f7a507956: Pull complete
be114a9a8114: Pull complete
45dc2aeacf0f: Pull complete
61f4890ae9e0: Pull complete
78c584710fa3: Pull complete
e2e96665ef7b: Pull complete
2dea12204f19: Pull complete
cf4c0fca6106: Pull complete
e91f057e0113: Pull complete
e34acb42f31a: Pull complete
323b84cdd649: Pull complete
0bd63efdd7fc: Pull complete
Creating global_mysql_1       ... done
Creating global_mailcatcher_1 ... done
Creating global_gateway_1     ... done
Creating global_dns_1         ... done
Creating global_phpmyadmin_1  ... done
Waiting for mysql...
Waiting for mysql...
Waiting for mysql...
Waiting for mysql...

Copying required files...
Generating docker-compose.yml file...
done
Creating database
(node:61867) UnhandledPromiseRejectionWarning: Error: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Query.<anonymous> (/usr/local/lib/node_modules/wp-local-docker/src/database.js:21:25)
    at Query.<anonymous> (/usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/Connection.js:525:10)
    at Query._callback (/usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/Connection.js:491:16)
    at Query.Sequence.end (/usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at /usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/Protocol.js:404:18
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/wp-local-docker/node_modules/mysql/lib/protocol/Protocol.js:403:13
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
(node:61867) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61867) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by dustinrue** [comment]
@selfagency If you have used a mysql image in the past it is possible that you have an existing mysqlData volume on your system already. Try `docker volume ls -f name=global_mysqlData`. If you get something back, and you know you don't need it for some other project then you can delete it with `docker volume rm global_mysqlData`

**Comment by jom** [comment]
I'm also getting this with a fresh install of Docker (no volumes).

**Comment by tylercherpak** [comment]
Hey all, I think this is resolved in the latest version. If you are still having issues let us know and I can reopen this issue. Thanks!
