### ISSUE TITLE
MySQL error on start

### ISSUE THREAD

**Issue by mwm-webdesign** [10up/wp-local-docker-v2#54]
When I start a project I get this error :

> Locating project files for testsite-test
> Ensuring global network exists
>  - Network exists
> Ensuring global cache volume exists
>  - Creating Volume
> Ensuring global services are running
> global_mailcatcher_1 is up-to-date
> global_mysql_1 is up-to-date
> global_gateway_1 is up-to-date
> global_dns_1 is up-to-date
> global_phpmyadmin_1 is up-to-date
> Waiting for mysql...
> child_process.js:660
>     throw err;
>     ^
> 
> Error: spawnSync /bin/sh ENOBUFS
>     at Object.spawnSync (internal/child_process.js:1041:20)
>     at spawnSync (child_process.js:607:24)
>     at execSync (child_process.js:652:15)
>     at Timeout._onTimeout (/home/mike/.npm-global/lib/node_modules/wp-local-docker/src/gateway.js:88:25)
>     at listOnTimeout (internal/timers.js:531:17)
>     at processTimers (internal/timers.js:475:7) {
>   errno: 'ENOBUFS',
>   code: 'ENOBUFS',
>   syscall: 'spawnSync /bin/sh',
>   path: '/bin/sh',
>   spawnargs: [ '-c', 'docker-compose logs mysql' ],
>   error: [Circular],
>   status: null,
>   signal: 'SIGTERM',
>   output: [
>     null,
>     <Buffer 41 74 74 61 63 68 69 6e 67 20 74 6f 20 67 6c 6f 62 61 6c 5f 6d 79 73 71 6c 5f 31 0a 1b 5b 33 36 6d 6d 79 73 71 6c 5f 31 20 20 20 20 20 20 20 20 7c 1b ... 1048873 more bytes>,
>     <Buffer >
>   ],
>   pid: 14569,
>   stdout: <Buffer 41 74 74 61 63 68 69 6e 67 20 74 6f 20 67 6c 6f 62 61 6c 5f 6d 79 73 71 6c 5f 31 0a 1b 5b 33 36 6d 6d 79 73 71 6c 5f 31 20 20 20 20 20 20 20 20 7c 1b ... 1048873 more bytes>,
>   stderr: <Buffer >
> }
> 

This has just started happening after I ran a system update (Manjaro Linux)
10updocker is the latest version.

edit : I get the same error when trying to create a new project

**Comment by mwm-webdesign** [comment]
The problem is solved after updating the Docker images with : `10updocker image update`
