### ISSUE TITLE
10updocker create error

### ISSUE THREAD

**Issue by chillbits-legacy** [10up/wp-local-docker-v2#98]
**Describe the bug**
Hello,

I am facing a problem while running the `10updocker create` command.

I got error like this:

```
~/.nvm/versions/node/v11.10.1/lib/node_modules/wp-local-docker/global$ 10updocker create
WARNING: No swap limit support
? What is the primary hostname for your site? (Ex: docker.test) localhost
? Are there additional domains the site should respond to? No
? Do you want to set a proxy for media assets? (i.e. Serving /uploads/ directory assets from a production site) No
? What version of PHP would you like to use? 7.3
? Do you need Elasticsearch Yes
? Do you want to install WordPress? Yes
? Select a WordPress installation type: Single Site
? Do you want to remove the default content? Yes
? Site Name localhost
? Admin Username admin
? Admin Password password
? Admin Email admin@example.com
Ensuring global network exists
 - Network exists
Ensuring global cache volume exists
 - Creating Volume
Ensuring global services are running
Traceback (most recent call last):
  File "/snap/docker/423/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.23.2', 'console_scripts', 'docker-compose')()
  File "/snap/docker/423/lib/python2.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/snap/docker/423/lib/python2.7/site-packages/compose/cli/main.py", line 124, in perform_command
    project = project_from_options('.', options)
  File "/snap/docker/423/lib/python2.7/site-packages/compose/cli/command.py", line 27, in project_from_options
    environment = Environment.from_env_file(override_dir or project_dir)
  File "/snap/docker/423/lib/python2.7/site-packages/compose/config/environment.py", line 61, in from_env_file
    instance = _initialize()
  File "/snap/docker/423/lib/python2.7/site-packages/compose/config/environment.py", line 57, in _initialize
    return cls(env_vars_from_file(env_file_path))
  File "/snap/docker/423/lib/python2.7/site-packages/compose/config/environment.py", line 35, in env_vars_from_file
    with contextlib.closing(codecs.open(filename, 'r', 'utf-8-sig')) as fileobj:
  File "/snap/docker/423/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: u'./.env'
(node:10928) UnhandledPromiseRejectionWarning: Error: Command failed: docker-compose up -d
    at checkExecSyncError (child_process.js:637:11)
    at execSync (child_process.js:674:13)
    at startGateway (/home/sondoha/.nvm/versions/node/v11.10.1/lib/node_modules/wp-local-docker/src/gateway.js:114:5)
    at Object.startGlobal (/home/sondoha/.nvm/versions/node/v11.10.1/lib/node_modules/wp-local-docker/src/gateway.js:138:11)
(node:10928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to Reproduce**

1. Install 10updocker from npm.
2. Run `10updocker configure`
3. Run `10updocker create` and follow instructions.

**Expected behavior**

Expect to use WP Docker.

**Screenshots**

**Environment information**
 - Device: PC
 - OS: Ubuntu 19.04
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by tylercherpak** [comment]
Hi @chillbits-legacy 

Are you still experiencing this issue on the latest version or wp-local-docker. I recommend following the troubleshooting steps [here](github.com/10up/wp-local-docker-v2/#i-am-having-issues-with-wp-local-docker-what-are-the-best-troubleshooting-techniques). Let us know if you are still having issues. Thanks!

**Comment by tylercherpak** [comment]
Hey @chillbits-legacy 

I am going to close this issue but if you are still having issues let us know and we will reopen this issue. Thanks!
